import { effectiveUiLanguage, localizedRecord } from "./i18n";
const en = {
  sourceHelp: "Automatic detection is supported, or you can choose the dialogue language.",
  title: "Local models", cloud: "Cloud services", custom: "Custom services",
  privacy: "Audio stays on this Mac. Translation is configured separately and may send text to a cloud service.",
  unavailable: "Requires Apple Silicon and macOS 14 or later.", loadFailed: "Could not load model status.",
  light: "Lightweight · recommended", standard: "Higher accuracy",
  download: "Download", use: "Use model", installed: "Downloaded", missing: "Not downloaded",
  downloading: "Downloading", verifying: "Verifying", cancelling: "Cancelling", deleting: "Deleting",
  inUse: "In use", delete: "Delete model", deleteConfirm: "Delete this downloaded model? Its configurations remain and you can download it again.",
  downloadFailed: "Download failed. Check your connection and retry.", integrityFailed: "Verification failed. Download the model again.", storageFailed: "Could not save the model. Check available disk space and folder permissions.",
  recognitionFailed: "Local recognition failed. Retry or choose a smaller model.",
  busy: "This model is busy. Stop recognition before deleting it.", ready: "Model downloaded", deleted: "Model deleted", retry: "Retry", retryStatus: "Refresh status",
};
type Copy = typeof en;
const copies: Record<ReturnType<typeof effectiveUiLanguage>, Copy> = {
  en,
  zh: {sourceHelp:"支持自动识别，也可以直接选择对白语言。",recognitionFailed:"本地识别失败，请重试或换用轻量模型。",title:"本地模型",cloud:"云端服务",custom:"自定义服务",privacy:"音频留在这台 Mac。翻译单独配置，使用云端翻译时会发送识别文字。",unavailable:"需要 Apple 芯片和 macOS 14 或更新版本。",loadFailed:"模型状态加载失败。",light:"轻量 · 推荐",standard:"更高准确率",download:"下载",use:"使用模型",installed:"已下载",missing:"未下载",downloading:"下载中",verifying:"校验中",cancelling:"取消中",deleting:"删除中",inUse:"使用中",delete:"删除模型",deleteConfirm:"删除已下载的模型？配置会保留，需要时可以重新下载。",downloadFailed:"下载失败，请检查网络后重试。",integrityFailed:"校验失败，请重新下载模型。",storageFailed:"模型保存失败，请检查磁盘空间和文件夹权限。",busy:"模型正在使用，请停止识别后再删除。",ready:"模型已下载",deleted:"模型已删除",retry:"重试",retryStatus:"刷新状态"},
  "zh-TW": {sourceHelp:"支援自動辨識，也可以直接選擇對白語言。",recognitionFailed:"本機辨識失敗，請重試或改用輕量模型。",title:"本機模型",cloud:"雲端服務",custom:"自訂服務",privacy:"音訊保留在這台 Mac。翻譯另行設定，使用雲端翻譯時會傳送辨識文字。",unavailable:"需要 Apple 晶片及 macOS 14 或更新版本。",loadFailed:"無法載入模型狀態。",light:"輕量 · 推薦",standard:"更高準確率",download:"下載",use:"使用模型",installed:"已下載",missing:"未下載",downloading:"下載中",verifying:"驗證中",cancelling:"取消中",deleting:"刪除中",inUse:"使用中",delete:"刪除模型",deleteConfirm:"刪除已下載的模型？設定會保留，之後可以重新下載。",downloadFailed:"下載失敗，請檢查網路後重試。",integrityFailed:"驗證失敗，請重新下載模型。",storageFailed:"無法儲存模型，請檢查磁碟空間和資料夾權限。",busy:"模型正在使用，請停止辨識後再刪除。",ready:"模型已下載",deleted:"模型已刪除",retry:"重試",retryStatus:"重新整理狀態"},
  ja: {sourceHelp:"自動検出に対応しています。会話の言語を指定することもできます。",recognitionFailed:"ローカル認識に失敗しました。再試行するか、軽量モデルを選んでください。",title:"ローカルモデル",cloud:"クラウドサービス",custom:"カスタムサービス",privacy:"音声はこの Mac 内で処理されます。翻訳は別に設定し、クラウド翻訳では認識したテキストを送信します。",unavailable:"Apple シリコンと macOS 14 以降が必要です。",loadFailed:"モデルの状態を取得できませんでした。",light:"軽量 · おすすめ",standard:"より高精度",download:"ダウンロード",use:"モデルを使用",installed:"ダウンロード済み",missing:"未ダウンロード",downloading:"ダウンロード中",verifying:"検証中",cancelling:"キャンセル中",deleting:"削除中",inUse:"使用中",delete:"モデルを削除",deleteConfirm:"モデルを削除しますか？設定は保持され、後から再ダウンロードできます。",downloadFailed:"ダウンロードに失敗しました。接続を確認して再試行してください。",integrityFailed:"検証に失敗しました。モデルを再ダウンロードしてください。",storageFailed:"保存できません。空き容量とフォルダの権限を確認してください。",busy:"モデルは使用中です。認識を停止してから削除してください。",ready:"モデルをダウンロードしました",deleted:"モデルを削除しました",retry:"再試行",retryStatus:"状態を更新"},
  de: {sourceHelp:"Automatische Erkennung wird unterstützt. Sie können auch die Dialogsprache auswählen.",recognitionFailed:"Lokale Erkennung fehlgeschlagen. Erneut versuchen oder ein kleineres Modell wählen.",title:"Lokale Modelle",cloud:"Cloud-Dienste",custom:"Eigene Dienste",privacy:"Audio bleibt auf diesem Mac. Übersetzung wird separat eingerichtet und kann Text an einen Cloud-Dienst senden.",unavailable:"Erfordert Apple Silicon und macOS 14 oder neuer.",loadFailed:"Modellstatus konnte nicht geladen werden.",light:"Leichtgewichtig · empfohlen",standard:"Höhere Genauigkeit",download:"Herunterladen",use:"Modell verwenden",installed:"Heruntergeladen",missing:"Nicht heruntergeladen",downloading:"Wird geladen",verifying:"Wird geprüft",cancelling:"Wird abgebrochen",deleting:"Wird gelöscht",inUse:"In Verwendung",delete:"Modell löschen",deleteConfirm:"Dieses Modell löschen? Die Konfigurationen bleiben erhalten. Sie können es erneut herunterladen.",downloadFailed:"Download fehlgeschlagen. Verbindung prüfen und erneut versuchen.",integrityFailed:"Prüfung fehlgeschlagen. Modell erneut herunterladen.",storageFailed:"Speichern fehlgeschlagen. Speicherplatz und Ordnerrechte prüfen.",busy:"Modell wird verwendet. Erkennung vor dem Löschen stoppen.",ready:"Modell heruntergeladen",deleted:"Modell gelöscht",retry:"Erneut versuchen",retryStatus:"Status aktualisieren"},
  ko: {sourceHelp:"자동 감지를 지원하며 대화 언어를 직접 선택할 수도 있습니다.",recognitionFailed:"로컬 인식에 실패했습니다. 다시 시도하거나 더 작은 모델을 선택하세요.",title:"로컬 모델",cloud:"클라우드 서비스",custom:"사용자 지정 서비스",privacy:"오디오는 이 Mac에서 처리됩니다. 번역은 별도로 설정하며 클라우드 번역 시 인식된 텍스트를 전송합니다.",unavailable:"Apple Silicon 및 macOS 14 이상이 필요합니다.",loadFailed:"모델 상태를 불러오지 못했습니다.",light:"경량 · 추천",standard:"높은 정확도",download:"다운로드",use:"모델 사용",installed:"다운로드됨",missing:"다운로드 안 됨",downloading:"다운로드 중",verifying:"검증 중",cancelling:"취소 중",deleting:"삭제 중",inUse:"사용 중",delete:"모델 삭제",deleteConfirm:"이 모델을 삭제할까요? 설정은 유지되며 다시 다운로드할 수 있습니다.",downloadFailed:"다운로드에 실패했습니다. 연결을 확인하고 다시 시도하세요.",integrityFailed:"검증에 실패했습니다. 모델을 다시 다운로드하세요.",storageFailed:"저장하지 못했습니다. 디스크 공간과 폴더 권한을 확인하세요.",busy:"모델을 사용 중입니다. 인식을 중지한 후 삭제하세요.",ready:"모델 다운로드 완료",deleted:"모델 삭제 완료",retry:"다시 시도",retryStatus:"상태 새로 고침"},
  fr: {sourceHelp:"La détection automatique est prise en charge. Vous pouvez aussi choisir la langue du dialogue.",recognitionFailed:"Échec de la reconnaissance locale. Réessayez ou choisissez un modèle plus léger.",title:"Modèles locaux",cloud:"Services cloud",custom:"Services personnalisés",privacy:"L’audio reste sur ce Mac. La traduction se configure séparément et peut envoyer du texte à un service cloud.",unavailable:"Nécessite Apple Silicon et macOS 14 ou ultérieur.",loadFailed:"Impossible de charger l’état des modèles.",light:"Léger · recommandé",standard:"Précision accrue",download:"Télécharger",use:"Utiliser le modèle",installed:"Téléchargé",missing:"Non téléchargé",downloading:"Téléchargement",verifying:"Vérification",cancelling:"Annulation",deleting:"Suppression",inUse:"En cours d’utilisation",delete:"Supprimer le modèle",deleteConfirm:"Supprimer ce modèle ? Les configurations sont conservées et vous pourrez le télécharger à nouveau.",downloadFailed:"Échec du téléchargement. Vérifiez la connexion et réessayez.",integrityFailed:"Échec de la vérification. Téléchargez à nouveau le modèle.",storageFailed:"Impossible d’enregistrer le modèle. Vérifiez l’espace disque et les autorisations du dossier.",busy:"Modèle utilisé. Arrêtez la reconnaissance avant de le supprimer.",ready:"Modèle téléchargé",deleted:"Modèle supprimé",retry:"Réessayer",retryStatus:"Actualiser l’état"},
};
export const LOCAL_MODEL_COPY = localizedRecord(() => copies[effectiveUiLanguage()]);
export function localModelError(error: unknown): string {
  const label = String(error);
  if (["runtime", "setup", "health", "audio", "finalize", "not_connected", "result_backlog"].some(part => label.includes(part))) return LOCAL_MODEL_COPY.recognitionFailed;
  if (label.includes("integrity")) return LOCAL_MODEL_COPY.integrityFailed;
  if (label.includes("storage")) return LOCAL_MODEL_COPY.storageFailed;
  if (label.includes("busy")) return LOCAL_MODEL_COPY.busy;
  if (label.includes("unavailable")) return LOCAL_MODEL_COPY.unavailable;
  return LOCAL_MODEL_COPY.downloadFailed;
}
