import { effectiveUiLanguage } from "./i18n";

const labels = {
  own: ["使用自己的模型", "使用自己的模型", "Use your own model", "自分のモデルを使う", "내 모델 사용", "Utiliser son modèle", "Eigenes Modell verwenden"],
  connect: ["连接已有服务", "連線現有服務", "Connect a service", "既存のサービスに接続", "기존 서비스 연결", "Connecter un service", "Dienst verbinden"],
  connectHelp: ["填写已运行的语音服务地址和模型名。请选择它支持的实时接口协议。", "填寫已執行的語音服務位址和模型名稱，並選擇支援的即時介面協定。", "Enter the URL and model name of a running speech service, using its realtime protocol.", "起動済み音声サービスの URL とモデル名を入力し、対応するリアルタイム方式を選択します。", "실행 중인 음성 서비스의 주소와 모델 이름을 입력하고 지원하는 실시간 프로토콜을 선택하세요.", "Saisissez l’URL et le modèle d’un service vocal actif, avec son protocole temps réel.", "URL und Modell eines laufenden Sprachdienstes mit dessen Echtzeitprotokoll eingeben."],
  programHelp: ["选择本机的识别程序和模型，Mimi 会在检查或识别时运行它，停止后结束程序。模型文件由你管理。", "選擇本機辨識程式和模型，Mimi 會在檢查或辨識時執行，停止後結束程式。模型檔案由你管理。", "Choose a local speech program and model. Mimi runs it only for checks or recognition and stops it with the session. You manage the model files.", "ローカルの認識プログラムとモデルを選択します。確認・認識時だけ起動し、停止時に終了します。モデルファイルは自分で管理します。", "로컬 인식 프로그램과 모델을 선택하세요. 확인 또는 인식할 때만 실행하며 세션 종료 시 중지합니다. 모델 파일은 직접 관리합니다.", "Choisissez un programme vocal local et un modèle. Mimi le lance pour un test ou une session, puis l’arrête. Vous gérez les fichiers du modèle.", "Lokales Spracherkennungsprogramm und Modell wählen. Mimi startet es nur zur Prüfung oder Erkennung und beendet es mit der Sitzung. Modelldateien verwalten Sie selbst."],
  protocol: ["接口协议", "介面協定", "Protocol", "接続方式", "프로토콜", "Protocole", "Protokoll"],
  engine: ["识别引擎", "辨識引擎", "Engine", "認識エンジン", "인식 엔진", "Moteur", "Erkennungsengine"],
  worker: ["兼容 Mimi 的程序", "相容 Mimi 的程式", "Mimi-compatible worker", "Mimi 対応プログラム", "Mimi 호환 프로그램", "Programme compatible Mimi", "Mimi-kompatibles Programm"],
  executable: ["执行程序", "執行程式", "Executable", "実行プログラム", "실행 프로그램", "Exécutable", "Ausführbare Datei"],
  chooseProgram: ["选择程序", "選擇程式", "Choose program", "プログラムを選択", "프로그램 선택", "Choisir un programme", "Programm wählen"],
  model: ["模型位置", "模型位置", "Model location", "モデルの場所", "모델 위치", "Emplacement du modèle", "Modellpfad"],
  chooseModel: ["选择文件", "選擇檔案", "Choose file", "ファイルを選択", "파일 선택", "Choisir un fichier", "Datei wählen"],
  chooseFolder: ["选择文件夹", "選擇資料夾", "Choose folder", "フォルダを選択", "폴더 선택", "Choisir un dossier", "Ordner wählen"],
  advanced: ["启动参数", "啟動參數", "Launch arguments", "起動引数", "실행 인수", "Arguments de lancement", "Startargumente"],
  argumentsHelp: ["每行一个参数，无需加引号。兼容程序可用 {model} 和 {language} 代入模型位置与识别语言。whisper.cpp 的模型、音频和输出参数由 Mimi 自动填写。", "每行一個參數，無需引號。相容程式可用 {model} 和 {language} 代入模型位置與辨識語言。whisper.cpp 的模型、音訊及輸出參數由 Mimi 自動填寫。", "One argument per line, without quotes. Workers may use {model} and {language}. Mimi supplies whisper.cpp model, audio and output options.", "引数は引用符を付けずに1行ずつ入力します。対応プログラムでは {model} と {language} を使えます。whisper.cpp のモデル・音声・出力は自動設定します。", "따옴표 없이 한 줄에 인수 하나를 입력하세요. 호환 프로그램은 {model}, {language}를 사용할 수 있습니다. whisper.cpp의 모델·오디오·출력은 자동 설정됩니다.", "Un argument par ligne, sans guillemets. Les programmes compatibles peuvent utiliser {model} et {language}. Les options de modèle, audio et sortie de whisper.cpp sont automatiques.", "Ein Argument je Zeile, ohne Anführungszeichen. Kompatible Programme können {model} und {language} verwenden. Modell-, Audio- und Ausgabeoptionen für whisper.cpp setzt Mimi automatisch."],
  whisperHelp: ["选择 whisper-cli 程序和 whisper.cpp 的 GGML .bin 模型。按短句识别，句末显示；每段会重新加载模型，速度取决于模型和硬件。", "選擇 whisper-cli 程式和 whisper.cpp 的 GGML .bin 模型。按短句辨識，句末顯示；每段重新載入模型，速度取決於模型與硬體。", "Choose whisper-cli and a whisper.cpp GGML .bin model. Results appear at sentence boundaries. The model reloads per turn; speed depends on the model and hardware.", "whisper-cli と whisper.cpp の GGML .bin モデルを選択します。文の区切りで表示し、各区間でモデルを読み込み直します。速度はモデルと機器によります。", "whisper-cli와 whisper.cpp GGML .bin 모델을 선택하세요. 문장 끝에서 결과를 표시하며 구간마다 모델을 다시 불러옵니다. 속도는 모델과 하드웨어에 따라 다릅니다.", "Choisissez whisper-cli et un modèle GGML .bin pour whisper.cpp. Les résultats arrivent en fin de phrase. Le modèle est rechargé à chaque segment ; la vitesse dépend du matériel.", "whisper-cli und ein whisper.cpp GGML-.bin-Modell wählen. Ergebnisse erscheinen am Satzende. Das Modell wird pro Abschnitt neu geladen; die Geschwindigkeit hängt von Modell und Hardware ab."],
  workerHelp: ["程序须实现 Mimi 的 JSON-lines 音频/字幕协议，通过标准输入输出通信。普通命令行程序不能直接选择此方式。", "程式須實作 Mimi 的 JSON-lines 音訊／字幕協定，透過標準輸入輸出通訊。一般命令列程式無法直接使用。", "The program must implement Mimi’s JSON-lines audio/subtitle protocol over stdin/stdout. Ordinary command-line programs need an adapter.", "標準入出力で Mimi の JSON-lines 音声・字幕プロトコルに対応したプログラムが必要です。通常の CLI にはアダプターが必要です。", "프로그램은 표준 입출력으로 Mimi JSON-lines 오디오·자막 프로토콜을 구현해야 합니다. 일반 명령줄 프로그램에는 어댑터가 필요합니다.", "Le programme doit gérer le protocole JSON-lines audio/sous-titres de Mimi via stdin/stdout. Un programme CLI ordinaire nécessite un adaptateur.", "Das Programm muss Mimis JSON-lines-Protokoll für Audio und Untertitel über stdin/stdout unterstützen. Normale CLI-Programme benötigen einen Adapter."],
  check: ["检查运行", "檢查執行", "Check program", "動作を確認", "실행 확인", "Tester le programme", "Programm prüfen"],
  save: ["保存配置", "儲存設定", "Save configuration", "設定を保存", "설정 저장", "Enregistrer", "Konfiguration speichern"],
  saved: ["本地程序配置已保存。", "本機程式設定已儲存。", "Local program saved.", "ローカルプログラムの設定を保存しました。", "로컬 프로그램 설정을 저장했습니다.", "Programme local enregistré.", "Lokales Programm gespeichert."],
  ready: ["已配置", "已設定", "Configured", "設定済み", "설정됨", "Configuré", "Konfiguriert"],
  missing: ["待配置", "待設定", "Setup needed", "設定が必要", "설정 필요", "À configurer", "Einrichtung erforderlich"],
  saveBeforeCheck: ["先保存更改，再检查运行。", "先儲存變更，再檢查執行。", "Save changes before checking the program.", "変更を保存してから動作を確認してください。", "변경 사항을 저장한 뒤 실행을 확인하세요.", "Enregistrez les modifications avant de tester.", "Änderungen vor der Prüfung speichern."],
  optionalKey: ["本机服务未设置密钥时可留空。", "本機服務未設定金鑰時可留空。", "Leave blank if your local service has no key.", "ローカルサービスにキーがなければ空欄で構いません。", "로컬 서비스에 키가 없으면 비워 두세요.", "Laissez vide si le service local n’a pas de clé.", "Leer lassen, wenn der lokale Dienst keinen Schlüssel verwendet."],
  executableError: ["请选择可执行的识别程序。", "請選擇可執行的辨識程式。", "Choose an executable speech program.", "実行可能な認識プログラムを選択してください。", "실행 가능한 인식 프로그램을 선택하세요.", "Choisissez un programme vocal exécutable.", "Ein ausführbares Erkennungsprogramm wählen."],
  modelError: ["找不到模型，请重新选择模型文件或文件夹。", "找不到模型，請重新選擇模型檔案或資料夾。", "Model not found. Choose its file or folder again.", "モデルが見つかりません。ファイルかフォルダを選び直してください。", "모델을 찾을 수 없습니다. 파일 또는 폴더를 다시 선택하세요.", "Modèle introuvable. Sélectionnez à nouveau son fichier ou dossier.", "Modell nicht gefunden. Datei oder Ordner erneut wählen."],
  argumentsError: ["启动参数无效。请每行填写一个参数，模型、音频和输出位置由 Mimi 设置。", "啟動參數無效。請每行填寫一個參數，模型、音訊及輸出位置由 Mimi 設定。", "Invalid launch arguments. Use one per line; Mimi controls model, audio and output paths.", "起動引数が無効です。1行ずつ入力し、モデル・音声・出力先は Mimi に任せてください。", "실행 인수가 잘못되었습니다. 한 줄에 하나씩 입력하세요. 모델·오디오·출력 경로는 Mimi가 설정합니다.", "Arguments invalides. Un par ligne ; Mimi gère les chemins du modèle, de l’audio et de sortie.", "Ungültige Startargumente. Ein Argument je Zeile; Modell-, Audio- und Ausgabepfade verwaltet Mimi."],
  runError: ["程序未能完成识别。请确认程序、模型格式和引擎匹配，再检查运行。", "程式未能完成辨識。請確認程式、模型格式與引擎相符，再檢查執行。", "Recognition failed. Check that the program, model format and engine match, then test again.", "認識に失敗しました。プログラム、モデル形式、エンジンの対応を確認し、再試行してください。", "인식에 실패했습니다. 프로그램·모델 형식·엔진이 맞는지 확인하고 다시 테스트하세요.", "Échec de la reconnaissance. Vérifiez la compatibilité du programme, du format du modèle et du moteur, puis réessayez.", "Erkennung fehlgeschlagen. Programm, Modellformat und Engine auf Kompatibilität prüfen und erneut testen."],
  timeout: ["本地识别超时。请换用更小的模型或检查启动参数。", "本機辨識逾時。請改用較小的模型或檢查啟動參數。", "Local recognition timed out. Try a smaller model or check launch arguments.", "ローカル認識がタイムアウトしました。小さいモデルか起動引数を確認してください。", "로컬 인식 시간이 초과되었습니다. 작은 모델을 쓰거나 실행 인수를 확인하세요.", "Délai de reconnaissance dépassé. Essayez un modèle plus petit ou vérifiez les arguments.", "Zeitüberschreitung bei lokaler Erkennung. Kleineres Modell versuchen oder Startargumente prüfen."],
  pickerError: ["无法打开文件选择器，请重试或手动填写完整路径。", "無法開啟檔案選擇器，請重試或手動填寫完整路徑。", "Could not open the picker. Retry or enter the full path.", "選択画面を開けません。再試行するかフルパスを入力してください。", "선택 창을 열 수 없습니다. 다시 시도하거나 전체 경로를 입력하세요.", "Impossible d’ouvrir le sélecteur. Réessayez ou saisissez le chemin complet.", "Dateiauswahl konnte nicht geöffnet werden. Erneut versuchen oder vollständigen Pfad eingeben."],
} as const;
const locales = ["zh", "zh-TW", "en", "ja", "ko", "fr", "de"] as const;
export const LOCAL_PROGRAM_COPY = new Proxy({} as Record<keyof typeof labels, string>, { get: (_, key: keyof typeof labels) => labels[key]?.[locales.indexOf(effectiveUiLanguage())] });

export function localProgramError(error: unknown): string {
  const label = error instanceof Error ? error.message : String(error);
  if (label.includes("executable") || label === "local_program_not_executable" || label === "local_program_start_failed") return LOCAL_PROGRAM_COPY.executableError;
  if (label.includes("model_")) return LOCAL_PROGRAM_COPY.modelError;
  if (label.includes("arguments")) return LOCAL_PROGRAM_COPY.argumentsError;
  if (label.includes("timeout")) return LOCAL_PROGRAM_COPY.timeout;
  if (label.includes("picker")) return LOCAL_PROGRAM_COPY.pickerError;
  if (label === "local_program_configuration_missing") return LOCAL_PROGRAM_COPY.missing;
  return LOCAL_PROGRAM_COPY.runError;
}
