// Shared locale shape keeps the Windows setup and privacy flow in parity.
export const WINDOWS_LIVE_CAPTIONS_COPY = {
  "en": {
    "windowsLiveCaptions": "Windows Live Captions",
    "windowsLiveCaptionsDescription": "Experimental · Reads locally recognized captions from the Windows Live Captions window through UI Automation. No recognition API key is required.",
    "windowsLiveCaptionsSetup": "Set up in Windows",
    "windowsLiveCaptionsStepOpen": "Open Live Captions (Win + Ctrl + L). Keep its window open while using mimi.",
    "windowsLiveCaptionsStepLanguage": "In Live Captions settings, download the required language pack and select the spoken language.",
    "windowsLiveCaptionsStepMicrophone": "Turn off “Include microphone audio” in Live Captions. mimi reads the captions Windows provides and cannot separate microphone captions.",
    "windowsLiveCaptionsLanguageHelp": "Declare the language selected in Windows Live Captions. This choice helps text translation; changing it here does not change the Windows recognition language.",
    "windowsLiveCaptionsConsent": "Allow mimi to read the text in the Windows Live Captions window",
    "windowsLiveCaptionsMicrophoneOff": "I have turned off “Include microphone audio” in Windows Live Captions",
    "windowsLiveCaptionsAllow": "Allow caption reading",
    "windowsLiveCaptionsAllowed": "Caption reading allowed",
    "windowsLiveCaptionsRevoke": "Revoke permission",
    "windowsLiveCaptionsStopAndRevoke": "Stop subtitles and revoke permission",
    "windowsLiveCaptionsConsentFailed": "Could not update caption-reading permission. Please try again.",
    "windowsLiveCaptionsOpen": "Open Live Captions",
    "windowsLiveCaptionsOpenFailed": "Could not open Live Captions. Press Win + Ctrl + L, then refresh the status.",
    "windowsLiveCaptionsRefresh": "Refresh status",
    "windowsLiveCaptionsLoading": "Checking Live Captions…",
    "windowsLiveCaptionsLoadFailed": "Could not check Live Captions. Refresh the status to try again.",
    "windowsLiveCaptionsUnsupported": "Requires Windows 11 version 22H2 or later. Choose another recognition service on this device.",
    "windowsLiveCaptionsClosed": "Live Captions is closed. Open it, complete Windows setup, then refresh the status.",
    "windowsLiveCaptionsSetupRequired": "Complete the language-pack setup in Windows Live Captions, then refresh the status.",
    "windowsLiveCaptionsReady": "Live Captions is ready",
    "windowsLiveCaptionsUnreadable": "The Live Captions window cannot be read. Keep its caption window open, then refresh the status. Windows updates may affect this experimental integration.",
    "windowsLiveCaptionsPrivacy": "Recognition stays in Windows. When translation is enabled, caption text is sent to the text translator you choose below; local recognition does not imply local translation.",
    "windowsLiveCaptionsOriginalPrivacy": "Original only: mimi does not send caption text to a translation service.",
    "windowsLiveCaptionsAudioUnavailable": "Live Captions provides text, not audio. Application selection, output-device selection, microphone / dual-source capture, and audio recording are unavailable with this service.",
    "windowsLiveCaptionsConsentRequired": "Allow caption reading and confirm microphone captions are off before starting.",
    "windowsLiveCaptionsNoTranslator": "To translate these captions, configure a text translator below, or enable Skip translation to show only the original."
  },
  "zh": {
    "windowsLiveCaptions": "Windows 实时字幕",
    "windowsLiveCaptionsDescription": "实验性 · 通过 UI Automation 读取 Windows「实时字幕」窗口中本地识别的文字，无需识别 API 密钥。",
    "windowsLiveCaptionsSetup": "在 Windows 中设置",
    "windowsLiveCaptionsStepOpen": "打开「实时字幕」（Win + Ctrl + L），使用 mimi 时保持其窗口开启。",
    "windowsLiveCaptionsStepLanguage": "在「实时字幕」设置中下载所需语言包，并选择实际说话的语言。",
    "windowsLiveCaptionsStepMicrophone": "关闭「实时字幕」中的「包括麦克风音频」。mimi 读取 Windows 提供的字幕，无法从中分离麦克风字幕。",
    "windowsLiveCaptionsLanguageHelp": "请选择 Windows「实时字幕」中已设置的语言。此处声明用于文字翻译；在 mimi 中更改不会修改 Windows 的识别语言。",
    "windowsLiveCaptionsConsent": "允许 mimi 读取 Windows「实时字幕」窗口中的文字",
    "windowsLiveCaptionsMicrophoneOff": "我已关闭 Windows「实时字幕」中的「包括麦克风音频」",
    "windowsLiveCaptionsAllow": "允许读取字幕",
    "windowsLiveCaptionsAllowed": "已允许读取字幕",
    "windowsLiveCaptionsRevoke": "撤销授权",
    "windowsLiveCaptionsStopAndRevoke": "停止字幕并撤销授权",
    "windowsLiveCaptionsConsentFailed": "无法更新字幕读取授权，请重试。",
    "windowsLiveCaptionsOpen": "打开实时字幕",
    "windowsLiveCaptionsOpenFailed": "无法打开「实时字幕」。请按 Win + Ctrl + L，然后刷新状态。",
    "windowsLiveCaptionsRefresh": "刷新状态",
    "windowsLiveCaptionsLoading": "正在检查实时字幕…",
    "windowsLiveCaptionsLoadFailed": "无法检查实时字幕，请刷新状态重试。",
    "windowsLiveCaptionsUnsupported": "需要 Windows 11 22H2 或更高版本。请在此设备选择其他识别服务。",
    "windowsLiveCaptionsClosed": "「实时字幕」尚未开启。请打开并完成 Windows 设置，然后刷新状态。",
    "windowsLiveCaptionsSetupRequired": "请在 Windows「实时字幕」中完成语言包设置，然后刷新状态。",
    "windowsLiveCaptionsReady": "实时字幕已就绪",
    "windowsLiveCaptionsUnreadable": "无法读取「实时字幕」窗口。请保持字幕窗口开启，然后刷新状态。Windows 更新可能影响此实验性功能。",
    "windowsLiveCaptionsPrivacy": "语音识别在 Windows 本地完成。启用翻译时，字幕文字会发送至下方选择的文字翻译服务；本地识别不代表本地翻译。",
    "windowsLiveCaptionsOriginalPrivacy": "仅显示原文：mimi 不会将字幕文字发送到翻译服务。",
    "windowsLiveCaptionsAudioUnavailable": "实时字幕只提供文字，不提供音频。此服务不支持选择应用、选择输出设备、麦克风或双声源采集，也不支持音频录制。",
    "windowsLiveCaptionsConsentRequired": "开始前请允许读取字幕，并确认已关闭麦克风字幕。",
    "windowsLiveCaptionsNoTranslator": "需要翻译时，请在下方配置文字翻译服务；也可启用「跳过翻译」仅显示原文。"
  },
  "zh-TW": {
    "windowsLiveCaptions": "Windows 即時字幕",
    "windowsLiveCaptionsDescription": "實驗性 · 透過 UI Automation 讀取 Windows「即時字幕」視窗中本機辨識的文字，無需辨識 API 金鑰。",
    "windowsLiveCaptionsSetup": "在 Windows 中設定",
    "windowsLiveCaptionsStepOpen": "開啟「即時字幕」（Win + Ctrl + L），使用 mimi 時保持其視窗開啟。",
    "windowsLiveCaptionsStepLanguage": "在「即時字幕」設定中下載所需語言套件，並選擇實際說話的語言。",
    "windowsLiveCaptionsStepMicrophone": "關閉「即時字幕」中的「包含麥克風音訊」。mimi 讀取 Windows 提供的字幕，無法分離麥克風字幕。",
    "windowsLiveCaptionsLanguageHelp": "請選擇 Windows「即時字幕」中已設定的語言。此處宣告用於文字翻譯；在 mimi 中更改不會修改 Windows 的辨識語言。",
    "windowsLiveCaptionsConsent": "允許 mimi 讀取 Windows「即時字幕」視窗中的文字",
    "windowsLiveCaptionsMicrophoneOff": "我已關閉 Windows「即時字幕」中的「包含麥克風音訊」",
    "windowsLiveCaptionsAllow": "允許讀取字幕",
    "windowsLiveCaptionsAllowed": "已允許讀取字幕",
    "windowsLiveCaptionsRevoke": "撤銷授權",
    "windowsLiveCaptionsStopAndRevoke": "停止字幕並撤銷授權",
    "windowsLiveCaptionsConsentFailed": "無法更新字幕讀取授權，請重試。",
    "windowsLiveCaptionsOpen": "開啟即時字幕",
    "windowsLiveCaptionsOpenFailed": "無法開啟「即時字幕」。請按 Win + Ctrl + L，然後重新整理狀態。",
    "windowsLiveCaptionsRefresh": "重新整理狀態",
    "windowsLiveCaptionsLoading": "正在檢查即時字幕…",
    "windowsLiveCaptionsLoadFailed": "無法檢查即時字幕，請重新整理狀態再試。",
    "windowsLiveCaptionsUnsupported": "需要 Windows 11 22H2 或更新版本。請在此裝置選擇其他辨識服務。",
    "windowsLiveCaptionsClosed": "「即時字幕」尚未開啟。請開啟並完成 Windows 設定，然後重新整理狀態。",
    "windowsLiveCaptionsSetupRequired": "請在 Windows「即時字幕」中完成語言套件設定，然後重新整理狀態。",
    "windowsLiveCaptionsReady": "即時字幕已就緒",
    "windowsLiveCaptionsUnreadable": "無法讀取「即時字幕」視窗。請保持字幕視窗開啟，然後重新整理狀態。Windows 更新可能影響此實驗性功能。",
    "windowsLiveCaptionsPrivacy": "語音辨識在 Windows 本機完成。啟用翻譯時，字幕文字會傳送至下方選擇的文字翻譯服務；本機辨識不代表本機翻譯。",
    "windowsLiveCaptionsOriginalPrivacy": "僅顯示原文：mimi 不會將字幕文字傳送到翻譯服務。",
    "windowsLiveCaptionsAudioUnavailable": "即時字幕僅提供文字，不提供音訊。此服務不支援選擇應用程式、輸出裝置、麥克風或雙聲源擷取，也不支援音訊錄製。",
    "windowsLiveCaptionsConsentRequired": "開始前請允許讀取字幕，並確認已關閉麥克風字幕。",
    "windowsLiveCaptionsNoTranslator": "需要翻譯時，請在下方設定文字翻譯服務；也可啟用「略過翻譯」僅顯示原文。"
  },
  "ja": {
    "windowsLiveCaptions": "Windows ライブ キャプション",
    "windowsLiveCaptionsDescription": "実験的機能 · UI Automation を通じて Windows のライブ キャプション画面からローカル認識された文字を読み取ります。認識用 API キーは不要です。",
    "windowsLiveCaptionsSetup": "Windows で設定",
    "windowsLiveCaptionsStepOpen": "ライブ キャプションを開き（Win + Ctrl + L）、mimi の使用中はウィンドウを開いたままにします。",
    "windowsLiveCaptionsStepLanguage": "ライブ キャプションの設定で必要な言語パックをダウンロードし、話されている言語を選びます。",
    "windowsLiveCaptionsStepMicrophone": "ライブ キャプションの「マイクの音声を含める」をオフにします。mimi は Windows の字幕を読み取り、マイクの字幕を分離できません。",
    "windowsLiveCaptionsLanguageHelp": "Windows のライブ キャプションで選んだ言語を指定してください。文字翻訳に使う宣言です。ここで変更しても Windows の認識言語は変わりません。",
    "windowsLiveCaptionsConsent": "mimi が Windows のライブ キャプション画面の文字を読み取ることを許可する",
    "windowsLiveCaptionsMicrophoneOff": "Windows のライブ キャプションで「マイクの音声を含める」をオフにしました",
    "windowsLiveCaptionsAllow": "字幕の読み取りを許可",
    "windowsLiveCaptionsAllowed": "字幕の読み取りを許可済み",
    "windowsLiveCaptionsRevoke": "許可を取り消す",
    "windowsLiveCaptionsStopAndRevoke": "字幕を停止して許可を取り消す",
    "windowsLiveCaptionsConsentFailed": "字幕の読み取り許可を更新できませんでした。再試行してください。",
    "windowsLiveCaptionsOpen": "ライブ キャプションを開く",
    "windowsLiveCaptionsOpenFailed": "開けませんでした。Win + Ctrl + L を押し、状態を更新してください。",
    "windowsLiveCaptionsRefresh": "状態を更新",
    "windowsLiveCaptionsLoading": "ライブ キャプションを確認中…",
    "windowsLiveCaptionsLoadFailed": "確認できませんでした。状態を更新してください。",
    "windowsLiveCaptionsUnsupported": "Windows 11 バージョン 22H2 以降が必要です。この端末では別の認識サービスを選んでください。",
    "windowsLiveCaptionsClosed": "ライブ キャプションが閉じています。開いて Windows の設定を完了し、状態を更新してください。",
    "windowsLiveCaptionsSetupRequired": "Windows のライブ キャプションで言語パックの設定を完了し、状態を更新してください。",
    "windowsLiveCaptionsReady": "ライブ キャプションは準備完了",
    "windowsLiveCaptionsUnreadable": "ウィンドウを読み取れません。字幕画面を開いたまま、状態を更新してください。Windows の更新によりこの実験的機能が影響を受けることがあります。",
    "windowsLiveCaptionsPrivacy": "認識は Windows 内で行われます。翻訳を有効にすると、字幕の文字は下で選んだ文字翻訳サービスに送信されます。ローカル認識はローカル翻訳を意味しません。",
    "windowsLiveCaptionsOriginalPrivacy": "原文のみ：mimi は字幕の文字を翻訳サービスに送信しません。",
    "windowsLiveCaptionsAudioUnavailable": "ライブ キャプションは文字のみを提供します。このサービスではアプリ、出力デバイス、マイク／二重音源の選択、および音声録音は利用できません。",
    "windowsLiveCaptionsConsentRequired": "開始前に字幕の読み取りを許可し、マイクの字幕がオフであることを確認してください。",
    "windowsLiveCaptionsNoTranslator": "翻訳するには下で文字翻訳を設定するか、「翻訳をスキップ」を有効にして原文のみを表示してください。"
  },
  "de": {
    "windowsLiveCaptions": "Windows Liveuntertitel",
    "windowsLiveCaptionsDescription": "Experimentell · Liest lokal erkannte Texte per UI Automation aus dem Windows-Liveuntertitel-Fenster. Kein API-Schlüssel zur Erkennung erforderlich.",
    "windowsLiveCaptionsSetup": "In Windows einrichten",
    "windowsLiveCaptionsStepOpen": "Öffne Liveuntertitel (Win + Strg + L). Lasse das Fenster während der Nutzung von mimi geöffnet.",
    "windowsLiveCaptionsStepLanguage": "Lade in den Liveuntertitel-Einstellungen das Sprachpaket herunter und wähle die gesprochene Sprache.",
    "windowsLiveCaptionsStepMicrophone": "Deaktiviere „Mikrofonaudio einschließen“. mimi liest Windows-Untertitel und kann Mikrofonuntertitel nicht trennen.",
    "windowsLiveCaptionsLanguageHelp": "Gib die in Windows-Liveuntertiteln ausgewählte Sprache an. Diese Angabe dient der Textübersetzung; sie ändert nicht die Erkennungssprache in Windows.",
    "windowsLiveCaptionsConsent": "mimi darf Text aus dem Windows-Liveuntertitel-Fenster lesen",
    "windowsLiveCaptionsMicrophoneOff": "Ich habe „Mikrofonaudio einschließen“ in Windows-Liveuntertiteln deaktiviert",
    "windowsLiveCaptionsAllow": "Lesen der Untertitel erlauben",
    "windowsLiveCaptionsAllowed": "Lesen der Untertitel erlaubt",
    "windowsLiveCaptionsRevoke": "Erlaubnis widerrufen",
    "windowsLiveCaptionsStopAndRevoke": "Untertitel stoppen und Erlaubnis widerrufen",
    "windowsLiveCaptionsConsentFailed": "Die Erlaubnis konnte nicht aktualisiert werden. Erneut versuchen.",
    "windowsLiveCaptionsOpen": "Liveuntertitel öffnen",
    "windowsLiveCaptionsOpenFailed": "Öffnen fehlgeschlagen. Drücke Win + Strg + L und aktualisiere den Status.",
    "windowsLiveCaptionsRefresh": "Status aktualisieren",
    "windowsLiveCaptionsLoading": "Liveuntertitel werden geprüft…",
    "windowsLiveCaptionsLoadFailed": "Prüfung fehlgeschlagen. Aktualisiere den Status.",
    "windowsLiveCaptionsUnsupported": "Windows 11 Version 22H2 oder neuer erforderlich. Wähle auf diesem Gerät einen anderen Erkennungsdienst.",
    "windowsLiveCaptionsClosed": "Liveuntertitel sind geschlossen. Öffne sie, schließe die Windows-Einrichtung ab und aktualisiere den Status.",
    "windowsLiveCaptionsSetupRequired": "Schließe die Sprachpaket-Einrichtung in Windows-Liveuntertiteln ab und aktualisiere den Status.",
    "windowsLiveCaptionsReady": "Liveuntertitel sind bereit",
    "windowsLiveCaptionsUnreadable": "Das Fenster ist nicht lesbar. Lasse es geöffnet und aktualisiere den Status. Windows-Updates können diese experimentelle Integration beeinflussen.",
    "windowsLiveCaptionsPrivacy": "Die Erkennung bleibt in Windows. Bei aktivierter Übersetzung wird der Untertiteltext an den unten gewählten Textübersetzer gesendet. Lokale Erkennung bedeutet keine lokale Übersetzung.",
    "windowsLiveCaptionsOriginalPrivacy": "Nur Original: mimi sendet keinen Untertiteltext an einen Übersetzungsdienst.",
    "windowsLiveCaptionsAudioUnavailable": "Liveuntertitel liefern Text, kein Audio. App- und Ausgabegeräteauswahl, Mikrofon- / Dualaufnahme sowie Audioaufzeichnung sind mit diesem Dienst nicht verfügbar.",
    "windowsLiveCaptionsConsentRequired": "Erlaube vor dem Start das Lesen der Untertitel und bestätige, dass Mikrofonuntertitel deaktiviert sind.",
    "windowsLiveCaptionsNoTranslator": "Richte unten einen Textübersetzer ein oder aktiviere Übersetzung überspringen, um nur das Original zu zeigen."
  },
  "fr": {
    "windowsLiveCaptions": "Sous-titres en direct Windows",
    "windowsLiveCaptionsDescription": "Expérimental · Lit par UI Automation le texte reconnu localement dans la fenêtre des sous-titres en direct Windows. Aucune clé API de reconnaissance requise.",
    "windowsLiveCaptionsSetup": "Configurer dans Windows",
    "windowsLiveCaptionsStepOpen": "Ouvrez les sous-titres en direct (Win + Ctrl + L). Gardez leur fenêtre ouverte pendant l’utilisation de mimi.",
    "windowsLiveCaptionsStepLanguage": "Dans leurs paramètres, téléchargez le pack linguistique et choisissez la langue parlée.",
    "windowsLiveCaptionsStepMicrophone": "Désactivez « Inclure l’audio du microphone ». mimi lit les sous-titres Windows et ne peut pas séparer ceux du microphone.",
    "windowsLiveCaptionsLanguageHelp": "Indiquez la langue choisie dans les sous-titres Windows. Cette déclaration sert à la traduction ; la modifier ici ne change pas la langue de reconnaissance Windows.",
    "windowsLiveCaptionsConsent": "Autoriser mimi à lire le texte de la fenêtre des sous-titres Windows",
    "windowsLiveCaptionsMicrophoneOff": "J’ai désactivé « Inclure l’audio du microphone » dans les sous-titres Windows",
    "windowsLiveCaptionsAllow": "Autoriser la lecture",
    "windowsLiveCaptionsAllowed": "Lecture des sous-titres autorisée",
    "windowsLiveCaptionsRevoke": "Révoquer l’autorisation",
    "windowsLiveCaptionsStopAndRevoke": "Arrêter les sous-titres et révoquer",
    "windowsLiveCaptionsConsentFailed": "Impossible de modifier l’autorisation. Réessayez.",
    "windowsLiveCaptionsOpen": "Ouvrir les sous-titres Windows",
    "windowsLiveCaptionsOpenFailed": "Ouverture impossible. Appuyez sur Win + Ctrl + L puis actualisez l’état.",
    "windowsLiveCaptionsRefresh": "Actualiser l’état",
    "windowsLiveCaptionsLoading": "Vérification des sous-titres Windows…",
    "windowsLiveCaptionsLoadFailed": "Vérification impossible. Actualisez l’état pour réessayer.",
    "windowsLiveCaptionsUnsupported": "Nécessite Windows 11 version 22H2 ou ultérieure. Choisissez un autre service sur cet appareil.",
    "windowsLiveCaptionsClosed": "La fenêtre est fermée. Ouvrez-la, terminez la configuration Windows puis actualisez l’état.",
    "windowsLiveCaptionsSetupRequired": "Terminez la configuration du pack linguistique dans Windows puis actualisez l’état.",
    "windowsLiveCaptionsReady": "Sous-titres Windows prêts",
    "windowsLiveCaptionsUnreadable": "La fenêtre est illisible. Gardez-la ouverte puis actualisez l’état. Les mises à jour Windows peuvent affecter cette intégration expérimentale.",
    "windowsLiveCaptionsPrivacy": "La reconnaissance reste dans Windows. Si la traduction est activée, le texte est envoyé au traducteur choisi ci-dessous. Reconnaissance locale ne signifie pas traduction locale.",
    "windowsLiveCaptionsOriginalPrivacy": "Original uniquement : mimi n’envoie aucun texte à un service de traduction.",
    "windowsLiveCaptionsAudioUnavailable": "Ce service fournit du texte, pas d’audio. La sélection d’application ou de sortie, la capture microphone / double source et l’enregistrement audio sont indisponibles.",
    "windowsLiveCaptionsConsentRequired": "Avant de démarrer, autorisez la lecture et confirmez que les sous-titres du microphone sont désactivés.",
    "windowsLiveCaptionsNoTranslator": "Configurez un traducteur ci-dessous ou activez Ignorer la traduction pour afficher uniquement l’original."
  },
  "ko": {
    "windowsLiveCaptions": "Windows 라이브 캡션",
    "windowsLiveCaptionsDescription": "실험적 기능 · UI Automation으로 Windows 라이브 캡션 창에서 로컬로 인식한 텍스트를 읽습니다. 인식 API 키는 필요하지 않습니다.",
    "windowsLiveCaptionsSetup": "Windows에서 설정",
    "windowsLiveCaptionsStepOpen": "라이브 캡션을 엽니다(Win + Ctrl + L). mimi를 사용하는 동안 창을 열어 두세요.",
    "windowsLiveCaptionsStepLanguage": "라이브 캡션 설정에서 언어 팩을 다운로드하고 실제로 말하는 언어를 선택하세요.",
    "windowsLiveCaptionsStepMicrophone": "라이브 캡션에서 “마이크 오디오 포함”을 끄세요. mimi는 Windows의 캡션을 읽으며 마이크 캡션을 분리할 수 없습니다.",
    "windowsLiveCaptionsLanguageHelp": "Windows 라이브 캡션에서 선택한 언어를 지정하세요. 텍스트 번역에 쓰는 선언이며, 여기서 변경해도 Windows 인식 언어는 바뀌지 않습니다.",
    "windowsLiveCaptionsConsent": "mimi가 Windows 라이브 캡션 창의 텍스트를 읽도록 허용",
    "windowsLiveCaptionsMicrophoneOff": "Windows 라이브 캡션에서 “마이크 오디오 포함”을 껐습니다",
    "windowsLiveCaptionsAllow": "캡션 읽기 허용",
    "windowsLiveCaptionsAllowed": "캡션 읽기 허용됨",
    "windowsLiveCaptionsRevoke": "권한 취소",
    "windowsLiveCaptionsStopAndRevoke": "자막을 중지하고 권한 취소",
    "windowsLiveCaptionsConsentFailed": "캡션 읽기 권한을 변경하지 못했습니다. 다시 시도하세요.",
    "windowsLiveCaptionsOpen": "라이브 캡션 열기",
    "windowsLiveCaptionsOpenFailed": "열지 못했습니다. Win + Ctrl + L을 누른 후 상태를 새로 고치세요.",
    "windowsLiveCaptionsRefresh": "상태 새로 고침",
    "windowsLiveCaptionsLoading": "라이브 캡션 확인 중…",
    "windowsLiveCaptionsLoadFailed": "확인하지 못했습니다. 상태를 새로 고쳐 다시 시도하세요.",
    "windowsLiveCaptionsUnsupported": "Windows 11 버전 22H2 이상이 필요합니다. 이 기기에서는 다른 인식 서비스를 선택하세요.",
    "windowsLiveCaptionsClosed": "라이브 캡션이 닫혀 있습니다. 열어서 Windows 설정을 마친 후 상태를 새로 고치세요.",
    "windowsLiveCaptionsSetupRequired": "Windows 라이브 캡션에서 언어 팩 설정을 마친 후 상태를 새로 고치세요.",
    "windowsLiveCaptionsReady": "라이브 캡션 준비 완료",
    "windowsLiveCaptionsUnreadable": "창을 읽을 수 없습니다. 캡션 창을 열어 두고 상태를 새로 고치세요. Windows 업데이트가 이 실험적 연동에 영향을 줄 수 있습니다.",
    "windowsLiveCaptionsPrivacy": "인식은 Windows 안에서 처리됩니다. 번역을 켜면 캡션 텍스트가 아래에서 선택한 번역기로 전송됩니다. 로컬 인식이 로컬 번역을 의미하지는 않습니다.",
    "windowsLiveCaptionsOriginalPrivacy": "원문만 표시: mimi는 캡션 텍스트를 번역 서비스로 전송하지 않습니다.",
    "windowsLiveCaptionsAudioUnavailable": "라이브 캡션은 텍스트만 제공합니다. 이 서비스에서는 앱, 출력 장치, 마이크 / 이중 소스 선택 및 오디오 녹음을 사용할 수 없습니다.",
    "windowsLiveCaptionsConsentRequired": "시작 전에 캡션 읽기를 허용하고 마이크 캡션이 꺼져 있는지 확인하세요.",
    "windowsLiveCaptionsNoTranslator": "번역하려면 아래에서 텍스트 번역기를 설정하거나 번역 건너뛰기를 켜서 원문만 표시하세요."
  }
} as const;
